import KeyMirror from 'key-mirror'

module.exports = KeyMirror({
  CP_AUDIO_INFO_GET: null,
  CP_AUDIO_INFO_GET_SUCCESS: null,
  CP_AUDIO_INFO_GET_FAILURE: null,
  CP_AUDIO_GOOD_CHANGE: null,
  CP_AUDIO_GOOD_CHANGE_SUCCESS: null,
  CP_AUDIO_GOOD_CHANGE_FAILURE: null,
  CP_AUDIO_GET_DOC: null,
  CP_AUDIO_GET_DOC_SUCCESS: null,
  CP_AUDIO_GET_DOC_FAILURE: null,
  CP_AUDIO_STORE: null,
  TOGGLE_AUDIO_POPOUT_BAR: null,
  SHOW_AUDIO_POPOUT_BAR: null,
  HIDE_AUDIO_POPOUT_BAR: null,
  SETTING_PLAYING_AUDIO_INFO: null,
  LOAD_CP_AUDIO_SUCCESS: null,
  LOAD_CP_AUDIO_FAILURE: null,
  // audio player types
  AUDIO_LOAD: null,
  AUDIO_LOADED: null,
  AUDIO_PLAY: null,
  AUDIO_PAUSE: null,
  AUDIO_SEEK: null,
  AUDIO_TO_NEXT_TRACK: null,
  AUDIO_TO_PREVIOUS_TRACK: null,
  AUDIO_UPDATE_INFO: null,
  AUDIO_UPDATE_CURRENT_TIME: null,
  // -----R_START--------------------
  ON_PRESS: null,
  ON_PRESS_REQUEST: null,
  ON_PRESS_SUCCESS: null,
  ON_PRESS_FAILURE: null,

  SAVE_PLAYING_AUDIO_STATIC_INFO: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_REQUEST: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_SUCCESS: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_FAILURE: null,

  SAVE_PLAYING_AUDIO_DYNAMIC_INFO: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_INFO_REQUEST: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_INFO_SUCCESS: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_CNFO_FAILURE: null
})
