import KeyMirror from 'key-mirror'

module.exports = KeyMirror({
  CP_AUDIO_INFO_GET: null,
  CP_AUDIO_INFO_GET_SUCCESS: null,
  CP_AUDIO_INFO_GET_FAILURE: null,
  CP_AUDIO_GET_DOC: null,
  CP_AUDIO_GET_DOC_SUCCESS: null,
  CP_AUDIO_GET_DOC_FAILURE: null,
  CP_AUDIO_STORE: null,
  TOGGLE_AUDIO_POPOUT_BAR: null,
  SHOW_AUDIO_POPOUT_BAR: null,
  HIDE_AUDIO_POPOUT_BAR: null,
  SETTING_PLAYING_AUDIO_INFO: null,
  LOAD_CP_AUDIO_SUCCESS: null,
  LOAD_CP_AUDIO_FAILURE: null,
  // audio player types
  AUDIO_LOAD: null,
  AUDIO_LOADED: null,
  AUDIO_SEEK: null,
  AUDIO_TO_NEXT_TRACK: null,
  AUDIO_TO_PREVIOUS_TRACK: null,
  AUDIO_UPDATE_INFO: null,
  // -----R_START--------------------

  SET_EVALUATION: null,
  SET_EVALUATION_REQUEST: null,
  SET_EVALUATION_SUCCESS: null,
  SET_EVALUATION_FAILURE: null,

  SET_LIKE_EVALUATION_ON_CAPSULE: null,
  SET_LIKE_EVALUATION_ON_CAPSULE_REQUEST: null,
  SET_LIKE_EVALUATION_ON_CAPSULE_SUCCESS: null,
  SET_LIKE_EVALUATION_ON_CAPSULE_FAILURE: null,

  REMOVE_LIKE_EVALUATION_ON_CAPSULE: null,
  REMOVE_LIKE_EVALUATION_ON_CAPSULE_REQUEST: null,
  REMOVE_LIKE_EVALUATION_ON_CAPSULE_SUCCESS: null,
  REMOVE_LIKE_EVALUATION_ON_CAPSULE_FAILURE: null,

  PLAY: null,
  PLAY_REQUEST: null,
  PLAY_SUCCESS: null,
  PLAY_FAILURE: null,

  PAUSE: null,
  PAUSE_REQUEST: null,
  PAUSE_SUCCESS: null,
  PAUSE_FAILURE: null,

  FORWARD_15: null,
  FORWARD_15_REQUEST: null,
  FORWARD_15_SUCCESS: null,
  FORWARD_15_FAILURE: null,

  BACKWARD_15: null,
  BACKWARD_15_REQUEST: null,
  BACKWARD_15_SUCCESS: null,
  BACKWARD_15_FAILURE: null,

  NEXT: null,
  NEXT_REQUEST: null,
  NEXT_SUCCESS: null,
  NEXT_FAILURE: null,

  PREVIOUS: null,
  PREVIOUS_REQUEST: null,
  PREVIOUS_SUCCESS: null,
  PREVIOUS_FAILURE: null,

  SEEK: null,
  SEEK_REQUEST: null,
  SEEK_SUCCESS: null,
  SEEK_FAILURE: null,

  TIMER: null,
  TIMER_REQUEST: null,
  TIMER_SUCCESS: null,
  TIMER_FAILURE: null,

  UPDATE_CURRENT_TIME: null,
  UPDATE_CURRENT_TIME_REQUEST: null,
  UPDATE_CURRENT_TIME_SUCCESS: null,
  UPDATE_CURRENT_TIME_FAILURE: null,

  REMOVE_COLOR: null,
  REMOVE_COLOR_REQUEST: null,
  REMOVE_COLOR_SUCCESS: null,
  REMOVE_COLOR_FAILURE: null,

  ADD_COLOR: null,
  ADD_COLOR_REQUEST: null,
  ADD_COLOR_SUCCESS: null,
  ADD_COLOR_FAILURE: null,

  AUDIO_PLAY: null,
  AUDIO_PLAY_REQUEST: null,
  AUDIO_PLAY_SUCCESS: null,
  AUDIO_PLAY_FAILURE: null,

  AUDIO_PAUSE: null,
  AUDIO_PAUSE_REQUEST: null,
  AUDIO_PAUSE_SUCCESS: null,
  AUDIO_PAUSE_FAILURE: null,

  ON_PRESS: null,
  ON_PRESS_REQUEST: null,
  ON_PRESS_SUCCESS: null,
  ON_PRESS_FAILURE: null,

  SAVE_PREVIOUS_KEY: null,
  SAVE_PREVIOUS_KEY_REQUEST: null,
  SAVE_PREVIOUS_KEY_SUCCESS: null,
  SAVE_PREVIOUS_KEY_FAILURE: null,

  SAVE_PLAYING_AUDIO_STATIC_INFO: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_REQUEST: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_SUCCESS: null,
  SAVE_PLAYING_AUDIO_STATIC_INFO_FAILURE: null,

  SAVE_PLAYING_AUDIO_DYNAMIC_INFO: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_INFO_REQUEST: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_INFO_SUCCESS: null,
  SAVE_PLAYING_AUDIO_DYNAMIC_CNFO_FAILURE: null
})
