import KeyMirror from 'key-mirror'

module.exports = KeyMirror({
  CP_AUDIO_INFO_GET: null,
  CP_AUDIO_INFO_GET_SUCCESS: null,
  CP_AUDIO_GOOD_CHANGE: null,
  CP_AUDIO_GOOD_CHANGE_SUCCESS: null,
  CP_AUDIO_GET_DOC: null,
  CP_AUDIO_GET_DOC_SUCCESS: null,
  TOGGLE_AUDIO_POPOUT_BAR: null,
  CHANGE_PLAYING_STATE: null,
  STORE_CAPSULE_AUDIOS: null,
  SETTING_PLAYING_AUDIO_INFO: null,
  LOAD_CP_AUDIO_SUCCESS: null
})
