import KeyMirror from 'key-mirror'

module.exports = KeyMirror({
  DOWNLOAD_CP_AUDIO: null,
  DOWNLOAD_CP_AUDIO_REQUEST: null,
  DOWNLOAD_CP_AUDIO_SUCCESS: null,
  DOWNLOAD_CP_AUDIO_FAILURE: null,

  GET_DOWNLOADED_CP_AUDIO: null,
  GET_DOWNLOADED_CP_AUDIO_REQUEST: null,
  GET_DOWNLOADED_CP_AUDIO_SUCCESS: null,
  GET_DOWNLOADED_CP_AUDIO_FAILURE: null,

  REMOVE_DOWNLOADED_CP_AUDIO: null,
  REMOVE_DOWNLOADED_CP_AUDIO_REQUEST: null,
  REMOVE_DOWNLOADED_CP_AUDIO_SUCCESS: null,
  REMOVE_DOWNLOADED_CP_AUDIO_FAILURE: null
})
