import { createActions } from 'redux-actions'
import {
  DOWNLOAD_CP_AUDIO,
  DOWNLOAD_CP_AUDIO_REQUEST,
  DOWNLOAD_CP_AUDIO_SUCCESS,
  DOWNLOAD_CP_AUDIO_FAILURE,
  GET_DOWNLOADED_CP_AUDIO,
  GET_DOWNLOADED_CP_AUDIO_REQUEST,
  GET_DOWNLOADED_CP_AUDIO_SUCCESS,
  GET_DOWNLOADED_CP_AUDIO_FAILURE,
  REMOVE_DOWNLOADED_CP_AUDIO,
  REMOVE_DOWNLOADED_CP_AUDIO_REQUEST,
  REMOVE_DOWNLOADED_CP_AUDIO_SUCCESS,
  REMOVE_DOWNLOADED_CP_AUDIO_FAILURE
} from './downloadTypes'

export default createActions({
  [DOWNLOAD_CP_AUDIO]: state => state,
  [DOWNLOAD_CP_AUDIO_REQUEST]: state => state,
  [DOWNLOAD_CP_AUDIO_SUCCESS]: state => state,
  [DOWNLOAD_CP_AUDIO_FAILURE]: state => state,
  [GET_DOWNLOADED_CP_AUDIO]: state => state,
  [GET_DOWNLOADED_CP_AUDIO_REQUEST]: state => state,
  [GET_DOWNLOADED_CP_AUDIO_SUCCESS]: state => state,
  [GET_DOWNLOADED_CP_AUDIO_FAILURE]: state => state,
  [REMOVE_DOWNLOADED_CP_AUDIO]: state => state,
  [REMOVE_DOWNLOADED_CP_AUDIO_REQUEST]: state => state,
  [REMOVE_DOWNLOADED_CP_AUDIO_SUCCESS]: state => state,
  [REMOVE_DOWNLOADED_CP_AUDIO_FAILURE]: state => state
})
