// @flow
import KeyMirror from 'key-mirror'

type memberKey = {
  
  GET_MEMBER_INFO: null,
  GET_MEMBER_INFO_REQUEST: null,
  GET_MEMBER_INFO_SUCCESS: null,
  GET_MEMBER_INFO_FAILURE: null,

  MEMBER_STATE_GET: null,
  MEMBER_STATE_GET_REQUEST: null,
  MEMBER_STATE_GET_SUCCESS: null,
  MEMBER_STATE_GET_FAILURE: null,

  SAVE_MEMBER_CHANGE: null,
  SAVE_MEMBER_CHANGE_REQUEST: null,
  SAVE_MEMBER_CHANGE_SUCCESS: null,
  SAVE_MEMBER_CHANGE_FAILURE: null,

  LOGOUT_MEMBER: null,
  LOGOUT_MEMBER_REQUEST: null,
  LOGOUT_MEMBER_SUCCESS: null,
  LOGOUT_MEMBER_FAILURE: null,

  LOGIN_MEMBER: null,
  LOGIN_MEMBER_REQUEST: null,
  LOGIN_MEMBER_SUCCESS: null,
  LOGIN_MEMBER_FAILURE: null,

  LOGIN_MEMBER_EMAIL: null,
  LOGIN_MEMBER_EMAIL_REQUEST: null,
  LOGIN_MEMBER_EMAIL_SUCCCESS: null,
  LOGIN_MEMBER_EMAIL_FAUILURE: null,

  CREATE_MEMBER: null,
  CREATE_MEMBER_REQUEST: null,
  CREATE_MEMBER_SUCCESS: null,
  CREATE_MEMBER_FAILURE: null,

  SEND_RESET_PASSWORD_EMAIL: null,
  SEND_RESET_PASSWORD_EMAIL_REQUEST: null,
  SEND_RESET_PASSWORD_EMAIL_SUCCESS: null,
  SEND_RESET_PASSWORD_EMAIL_FAILURE: null,

  CHANGE_MEMBER_STATE: null,
  CHANGE_MEMBER_STATE_REQUEST: null,
  CHANGE_MEMBER_STATE_SUCCESS: null,
  CHANGE_MEMBER_STATE_FAILURE: null,

  SEND_FEEDBACK: null,
  SEND_FEEDBACK_REQUEST: null,
  SEND_FEEDBACK_SUCCESS: null,
  SEND_FEEDBACK_FAILURE: null,

  MEMBER: null,
  MEMBER_REQUEST: null,
  MEMBER_FAIL: null,
  MEMBER_SUCCESS: null,

  SET_FAVORITE_CAPSULE_ON_USER: null,
  SET_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  SET_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  SET_FAVORITE_CAPSULE_ON_USER_FAILURE: null,

  REMOVE_FAVORITE_CAPSULE_ON_USER: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_FAILURE: null
}

const memberTypes: memberKey = {
  GET_MEMBER_INFO: null,
  GET_MEMBER_INFO_REQUEST: null,
  GET_MEMBER_INFO_SUCCESS: null,
  GET_MEMBER_INFO_FAILURE: null,

  MEMBER_STATE_GET: null,
  MEMBER_STATE_GET_REQUEST: null,
  MEMBER_STATE_GET_SUCCESS: null,
  MEMBER_STATE_GET_FAILURE: null,

  MEMBER_CAPSULE_GET: null,
  MEMBER_CAPSULE_GET_REQUEST: null,
  MEMBER_CAPSULE_GET_SUCCESS: null,
  MEMBER_CAPSULE_GET_FAILURE: null,

  SAVE_MEMBER_CHANGE: null,
  SAVE_MEMBER_CHANGE_REQUEST: null,
  SAVE_MEMBER_CHANGE_SUCCESS: null,
  SAVE_MEMBER_CHANGE_FAILURE: null,

  LOGOUT_MEMBER: null,
  LOGOUT_MEMBER_REQUEST: null,
  LOGOUT_MEMBER_SUCCESS: null,
  LOGOUT_MEMBER_FAILURE: null,

  LOGIN_MEMBER: null,
  LOGIN_MEMBER_REQUEST: null,
  LOGIN_MEMBER_SUCCESS: null,
  LOGIN_MEMBER_FAILURE: null,

  LOGIN_MEMBER_EMAIL: null,
  LOGIN_MEMBER_EMAIL_REQUEST: null,
  LOGIN_MEMBER_EMAIL_SUCCCESS: null,
  LOGIN_MEMBER_EMAIL_FAUILURE: null,

  CREATE_MEMBER: null,
  CREATE_MEMBER_REQUEST: null,
  CREATE_MEMBER_SUCCESS: null,
  CREATE_MEMBER_FAILURE: null,

  SEND_RESET_PASSWORD_EMAIL: null,
  SEND_RESET_PASSWORD_EMAIL_REQUEST: null,
  SEND_RESET_PASSWORD_EMAIL_SUCCESS: null,
  SEND_RESET_PASSWORD_EMAIL_FAILURE: null,

  CHANGE_MEMBER_STATE: null,
  CHANGE_MEMBER_STATE_REQUEST: null,
  CHANGE_MEMBER_STATE_SUCCESS: null,
  CHANGE_MEMBER_STATE_FAILURE: null,

  SEND_FEEDBACK: null,
  SEND_FEEDBACK_REQUEST: null,
  SEND_FEEDBACK_SUCCESS: null,
  SEND_FEEDBACK_FAILURE: null,

  MEMBER: null,
  MEMBER_REQUEST: null,
  MEMBER_FAIL: null,
  MEMBER_SUCCESS: null,

  SET_FAVORITE_CAPSULE_ON_USER: null,
  SET_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  SET_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  SET_FAVORITE_CAPSULE_ON_USER_FAILURE: null,

  REMOVE_FAVORITE_CAPSULE_ON_USER: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_FAILURE: null
}

module.exports = KeyMirror(memberTypes)
