// @flow
import KeyMirror from 'key-mirror'

type memberKey = {
  GET_MEMBER_INFO: null,
  MEMBER_STATE_GET_SUCCESS: null,
  MEMBER_STATE_GET_FAILURE: null,
  MEMBER_CAPSULE_GET: null,
  MEMBER_CAPSULE_GET_SUCCESS: null,
  SAVE_MEMBER_CHANGE: null,
  LOGOUT_MEMBER: null,
  LOGIN_MEMBER: null,
  LOGIN_MEMBER_EMAIL: null,
  CREATE_MEMBER: null,
  SEND_RESET_PASSWORD_EMAIL: null,
  CHANGE_MEMBER_STATE: null,
  SEND_FEEDBACK: null,
  SEND_FEEDBACK_SUCCESS: null,
  SEND_FEEDBACK_FAILURE: null,
  MEMBER_FAIL: null,
  MEMBER_SUCCESS: null,

  SET_FAVORITE_CAPSULE_ON_USER: null,
  SET_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  SET_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  SET_FAVORITE_CAPSULE_ON_USER_FAILURE: null,

  REMOVE_FAVORITE_CAPSULE_ON_USER: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_FAILURE: null,
}

const memberTypes: memberKey = {
  GET_MEMBER_INFO: null,
  MEMBER_STATE_GET_SUCCESS: null,
  MEMBER_STATE_GET_FAILURE: null,
  MEMBER_CAPSULE_GET: null,
  MEMBER_CAPSULE_GET_SUCCESS: null,
  SAVE_MEMBER_CHANGE: null,
  LOGOUT_MEMBER: null,
  LOGIN_MEMBER: null,
  LOGIN_MEMBER_EMAIL: null,
  CREATE_MEMBER: null,
  SEND_RESET_PASSWORD_EMAIL: null,
  CHANGE_MEMBER_STATE: null,
  SEND_FEEDBACK: null,
  SEND_FEEDBACK_SUCCESS: null,
  SEND_FEEDBACK_FAILURE: null,
  MEMBER_FAIL: null,
  MEMBER_SUCCESS: null,

  SET_FAVORITE_CAPSULE_ON_USER: null,
  SET_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  SET_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  SET_FAVORITE_CAPSULE_ON_USER_FAILURE: null,

  REMOVE_FAVORITE_CAPSULE_ON_USER: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_REQUEST: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_SUCCESS: null,
  REMOVE_FAVORITE_CAPSULE_ON_USER_FAILURE: null,
}

module.exports = KeyMirror(memberTypes)
