# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'talkTekApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for talkTekApp
  pod 'Google/SignIn'

  target 'talkTekApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'talkTekAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'talkTekApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for talkTekApp-tvOS

  target 'talkTekApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
